import requests
from bs4 import BeautifulSoup
from datetime import datetime

import app
company_symbol_dict={'1st.Fid.Leasing':'fid',
 '786 Invest Ltd':'786',
 'AGP Limited':'AGP',
 'AKD Securites':'AKD',
 'AL-Ghazi Tractors':'AGTL',
 'AL-Khair Gadoon':'AKGL',
 'AL-Noor Mod':'FANM',
 'AL-Noor Sugar':'ALNRS',
 'Abbott Lab.':'ABBT',
 'Abdullah Shah':'AGSML',
 'Adam Sugar':'ADAMS',
 'Adamjee Ins.':'AICL',
 'Adamjee Life Ass.':'ALIFE',
 'Agha Steel Ind.':'AGHA',
 'Agriautos Ind.':'AIGL',
 'Agritech Limited':'AGL',
 'Ahmed Hassan':'AHTM',
 'Air Link Commun':'AIRLINK',
 'Aisha Steel Mill':'ASL',
 'Aisha Steel(CPS)':'ASLCPS',
 'Aisha StelCoP/S':'ASL',
 'Al-Abbas Sugar':'AABS',
 'Al-Shaheer Corp':'ASC',
 'Alfalah Consumer':'ACIETF',
 'Ali Asghar Textile':'AATM',
 'Allied Bank Ltd':'ABL',
 'Altern Energy':'ALTN',
 'Amreli Steels':'ASTL',
 'Amtex Limited':'AMTEX',
 'Ansari Sugar':'ANSM',
 'Apna Microfin.':'AMBL',
 "Archroma Pak": "ARPL",
    "Arctic Textile": "ARCTM",
    "Arif Habib Corp": "AHCL",
    "Arif Habib Ltd.": "AHL",
    "Arpak Int.": "ARPAK",
    "Artistic Denim": "ADMM",
    "Aruj Industries": "ARUJ",
    "Ashfaq Textile": "ASHT",
    "Asia Insurance": "ASIC",
    "Asim Textile": "ASTM",
    "Ask.Gen.Insurance": "AGIC",
    "Askari Bank": "AKBL",
    "Askari Life Ass": "ALAC",
    "At-Tahur Ltd.": "PREMA",
    "Atlas Battery": "ATBA",
    "Atlas Honda Ltd": "ATLH",
    "Atlas Ins. Ltd": "ATIL",
    "Attock Cement": "ACPL",
    "Attock Petroleum": "APL",
"Attock Refinery": "ATRL",
    "Avanceon Ltd": "AVN",
    "Azgard Nine": "ANL",
    "Azgard(Non-Voti)": "ANLNV",
    "B.F.Modaraba": "BFMOD",
    "B.O.Punjab": "BOP",
    "B.R.R Guardia Ltd": "BRRG", # Future Contract for Bank AL Habib
    "BF Biosciences": "BFBIO",   # Future Contract for Bank of Punjab
    "Baba Farid": "BAFS",
    "Bal.Glass": "BGL",
  "Bal.WheelsXD": "BWHL",
    "Bank AL-Habib": "BAHL",
    "Bank Al-Falah": "BAFL",
    "Bank Makramah": "BML",
    "Bank Of Khyber": "BOKL",
    "Bankislami Pak": "BIPL",
    "Bannu Woollen": "BNWM",
    "Barkat Frisian Agro": "BFAL",
    "Bata (Pak) Ltd.": "BATA",
    "Bawany Air Prod": "BAPL",
    "Beco Steel Ltd": "BECO",
    "Bela Automotive": "BELA",
    "Berger Paints": "BERL",
    "Bestway Cement": "BWCL",
    "Bhanero Tex.": "BHAT",
"Biafo Industries": "BIFO",
    "Big Bird Foods Ltd.": "BBFL",
    "Blue-Ex Limited": "BLUEX",
    "Bolan Casting": "BCL",
    "Bunnys Limited": "BNL",
    "Burshane LPG": "BPL",
    "Buxly Paints": "BUXL", # Future Contract for Crescent Steel
    "Calcorp Limited": "CASH",
    "Century Ins.": "CENI",
    "Century Paper": "CEPB",
    "Chashma Sugar": "CHAS",
    "Chenab Limited": "CHBL",
    "Chenab Ltd.(Pre": "CHBLP" , # Cumulative Preference Shares

  "Cherat Cement": "CHCC",
    "Cherat Packaging": "CPPL",
    "Citi Pharma Ltd": "CPHL",
    "Clover Pakistan": "CLOV",
    "Cnergyico PK": "CNERGY",
    "Colgate Palm": "COLG",
    "Colony Tex.Mills Ltd": "CTM",
    "Cordoba Logist": "CLVL",
    "Cres.Star Ins.": "CSIL",
    "Crescent Fibres": "CRFG",
    "Crescent Jute": "CJUM",
    "Crescent SteelXD": "CSAP",
    "Crescent Tex.": "CRTM",
    "Cyan Limited": "CYAN",
    "D.G.K.Cement": "DGKC",
    "D.M. Corporation Ltd": "DMCO",
    "D.S. Ind. Ltd.": "DSIL",# Future Contract for Dewan Farooque Motors
 "DH Partners Ltd.": "DHPL",
    "Dadabhoy Cement": "DBCI",
    "Dadex Eternit": "DADX",
    "Dandot Cement": "DNCC",
    "Data Agro": "DAAG",
    "Dawood Equities": "DEL",
    "Dawood Law": "DLL",  # Dawood Lawrencepur Limited
    "Descon Oxychem": "DOL",
    "Dewan Auto Engg": "DWAE",
    "Dewan Cement": "DCL",
    "Dewan Farooque Sp.": "DFSM",  # Dewan Farooque Spinning Mills
    "Dewan Motors": "DFML",
    "Dewan Sugar": "DWSM",
    "Dewan Textile": "DWTM",
    "Din Textile": "DINT",
    "Dolmen City": "DCR",   # Dolmen City REIT
    "Dost Steels Ltd.": "DSL",
    "Dynea Pakistan": "DYNO",
    "ECOPACK Ltd": "ECOP",   # Future Contract for Engro Fertilizers
    "EFU General": "EFUG",
    "EFU Life Assurance": "EFUL",
    "EMCO Industries": "EMCO",    # Future Contract for Engro Polymer
    "Elahi Cotton": "ELCM",
    "Elite Cap.Mod": "ECAM",
    "Ellcot Spinning": "ELLCOT",
    "Engro Fertert": "EFERT",
    "Engro Holdings": "ENGRO",
    "Engro Poly (Pref)": "EPCLP", # Preference Shares
    "Engro Polymer": "EPCL",
    "Engro Powergen": "EPQL",
    "Equity Modaraba": "EQMOD",
    "Escorts Bank": "ESBL",
    "Exide (PAK)": "EXIDE",
    "F. Nat.Equities": "FNEL",
"F.Credit & Inv": "FCIBL",
    "F.Treet Manuf": "FTMM",  # Future Contract for Flying Cement
    "Faisal Spinning": "FASM",
    "Faran Sugar Mills": "FRSM",
    "Fast Cables Ltd.": "FCL",
    "Fateh Industries": "FIL",
    "Fateh Sports": "FSWL",
    "Fatima Fert": "FATIMA",
    "Fauji Cement": "FCCL",
 "Fauji Fert": "FFC",
    "Fauji Foods Ltd": "FFL",
    "Faysal Bank": "FABL",
    "Fazal Cloth": "FZCM",
    "Fecto Cement": "FECTC",
    "Feroze 1888": "FML",
    "Ferozsons (Lab)": "FEROZ",
    "First Cap.Equit": "FCE",
    "First Dawood Prop": "FDPL",
    "Flying Cement": "FLYNG",
    "Frieslandcampina": "FCEPL",
 "GOC (Pak) Ltd.": "GOC",
    "Gadoon Textile": "GADT",
    "Gammon Pak": "GAMON",
    "Gatron Ind.": "GATI",
    "Ghandhara Automobile": "GAL",
    "Ghandhara Ind.": "GHNI",
    "Ghandhara Tyre": "GTYR",
    "Ghani Chemical": "GCIL",
    "Ghani Chemworld": "GCWL",
    "Ghani Dairies Ltd.": "GDL",
    "Ghani Glass Ltd": "GHGL",
    "Ghani Glo Hol": "GGL",
    "Ghani Value Glass": "GVGL",
    "GhaniGlobalGlass": "GGGL",
    "Gharibwal Cement": "GWLC",
    "Ghazi Fabrics": "GFIL",
    "Gillette Pak": "GILL",
    "GlaxoSmithKline": "GLAXO",
    "Globe Residency": "GRR",  # Globe Residency REIT
    "Grays Leasing": "GRYL",
 "Gul Ahmed": "GATM",
    "Gulshan Sp.": "GSPM",
    "HBL Growth Fund": "HGFA",
    "HBL Invest Fund": "HIFA",
    "HBL Total Treasury": "HBLTETF",     # Future Contract for Habib Bank
    "HI-Tech Lub.": "HTL",  # Future Contract for Hum Network
    "Habib Bank": "HBL",
    "Habib Ins.": "HICL",
    "Habib Metropolitan": "HMB",
    "Habib Modaraba": "FHAM",     # First Habib Modaraba
    "Habib Rice Prod": "HRPL",
    "Habib Sugar": "HABSM",
    "Hafiz Limited": "HAEL",
    "Hala Enterprise": "HALA",
   "Haleon Pakistan": "HALEON",
    "Hascol Petrol": "HASCOL",
    "Highnoon (Lab)": "HINOON",
    "Hinopak Motor": "HINO",
    "Hira Textile": "HIRAT",
    "Hoechst Pak Ltd": "HLEL",
    "Honda Atlas Cars": "HCAR",
    "Hub Power Co.": "HUBC",
    "Hum Network": "HUMNL",
    "Hussain Industries": "HUSI",
    "I.B.L.Modarab": "IBLMC",
    "IBL HealthCare": "IBLHL",
    "ICC Industries": "ICCI",
    "IGI Holdings": "IGIHL",
 "Ibrahim Fibres": "IBFL",
    "Ideal Spinning": "IDSM",
    "Idrees Textile": "IDRT",
    "Image Pakistan": "IMAGE",
    "Image Reit": "IMREIT",
    "Imperial Limite": "IML",
    "Imrooz Modaraba": "FIMM",     # First Imrooz Modaraba
    "Indus Dyeing": "IDYM",
    "Indus Motor Co.": "INDU",
    "Int. Ind.Ltd.XD": "IIL",      # International Industries
    "Int. Packaging": "IPAK",
    "Int.Knitwear": "INKL",
    "Inter.Steel LtdXD": "ISL",    # International Steels
    "Interloop Ltd.XD": "ILP",
    "Intermarket Sec.": "IMS",
    "Invest Bank": "ICIBL",        # Invest Capital Investment Bank
    "Ismail Ind.": "ISIL",
 "Ist.Capital Sec": "FCSC",
  "Itanz Technologies": "ITANZ",
    "Ittefaq Iron Ind": "ITTEFAQ",
    "Ittehad Chemicals": "ICL",
    "J.A.Textile": "JATM",
    "J.D.W.Sugar": "JDWS",
    "JS Bank Ltd": "JSBL",
    "JS Global Banking": "JSGBETF",
    "JS Global Cap.": "JSGCL",
    "JS Investments": "JSIL",
    "JS Momentum": "JSMFETF",   # Future Contract for Javedan Corp
    "Jah.Sidd. Co.": "JSCL",
    "Janana D Mal": "JDMT",
    "Jauharabad Sug": "JAUHS",
    "Javedan Corp(Pr)": "JVDCPS", # Preference Shares
    "Javedan Corp.": "JVDC",
    "Jubile Life Ins": "JLIU",
    "Jubilee Gen.Ins": "JGICL",
    "Jubilee Spinning": "JUSM",
    "K-Electric Ltd.": "KEL",
 "K.S.B.Pumps": "KSBP", # Future Contract for Kohinoor Spinning
    "Khairpur Sugar": "KPUS",
    "Khalid Siraj": "KSTM",     # Khalid Siraj Textile Mills
    "Khyber Textile": "KHYT",
    "Khyber Tobacco": "KHTC",
    "Kohat Cement": "KOHC",
    "Kohat Textile": "KOTM",
 "Kohinoor Energy": "KOHE",
    "Kohinoor Ind.": "KOIL",
    "Kohinoor Mills": "KML",
    "Kohinoor Power": "KOHP",
    "Kohinoor Spining": "KOSM",
    "Kohinoor Textile": "KTML",
    "Kot Addu Power": "KAPCO",
    "LOADS Limited": "LOADS",  # Future Contract for Lotte Chemical
    "LSE Capital Ltd.": "LSECAP",
    "LSE Capital Ltd.(R)": "LSECAPR1", # Right Shares
    "LSE Fin. Services": "LSEFSL",
    "LSE Ventures Ltd": "LSEV",  # Future Company for Lucky Cement
    "Lalpir Power": "LPL",
    "Leather Up Ltd.": "LEUL",
    "Leiner Pak Gelat": "LPGL",
    "Liven Pharma": "LPL",          # Note: Usually Liven Pharma (LIVEN) - Verify if intended
    "Loads Limited": "LOADS",
    "Lotte Chemical": "LOTCHEM",
    "Lucky Cement": "LUCK",
    "Lucky Core Ind.": "LCI",
    "MACPAC Films": "MACFL",
    "MARI-FEBB": "MARI-FEB",        # Future Contract for Mari Petroleum
    "MCB Bank Ltd": "MCB",
    "MCB Inv MGTXD": "MCBAF",   # Future Contract for Mughal Steel
    "Macter Int. Ltd": "MACTER",
    "Mahaana Islamic": "MIIETF", # Mahaana Islamic Index ETF
    "Mandviwala": "MWMT",        # Mandviwala Mushtaq Machinery
    "Maple Leaf": "MLCF",        # Maple Leaf Cement Factory
    "Maqbool Textile": "MQTM",
    "Mari Energies Ltd.": "MARI", # Mari Petroleum (formerly Mari Gas)
    "Masood Textile": "MSOT",
    "Matco Foods Ltd": "MATCO",
    "Media Times Ltd": "WTL",     # Media Times (Associated with WorldCall)
    "Meezan Bank Ltd": "MEBL",
    "Meezan Pakistan": "MZNPAK", # Meezan Pakistan Exchange Traded Fund
    "Mehmood Tex.": "MEHT",
    "Mehran Sugar": "MRNS",
    "Merit Packaging": "MERIT",
"Metro Steel": "MSCL",
    "Millat Tractors": "MTL",
    "Mirpurkhas Sugar": "MIRKS",
    "MithchellsFruit": "MFFL",
    "Mughal Iron": "MUGH",
    "Mughal Iron(C)": "MUGHALC",
    "Murree Brewery": "MUREB",
    "NBP Pakistan G ETF": "NBPGETF",# Future Contract for Netsol Technologies
    "NIT Pakistan": "NITGETF",
 "Nagina Cotton": "NAGC",
    "National BankXD": "NBP",
    "National Foods": "NATF",
    "National Refinery": "NRL",
    "National Silk": "NSIL",
    "Nazir Cotton Mills": "NZCM",
    "Nestle Pakistan": "NESTLE",
    "Nets International": "NETS",
    "Netsol Tech.": "NETSOL",
    "Next Capital": "NEXT",
    "Nimir Ind.Chem": "NICL",
    "Nimir Resins": "NRSL",
    "Nishat (Chun.)": "NCL",
    "Nishat ChunPower": "NCPL",
    "Nishat Mills Ltd": "NML",
    "Nishat Power": "NPL",
    "Noon Sugar": "NOON",
"OLP Financial": "OLPL",
    "OLP Modaraba": "OLPM",
    "Octopus Digital": "OCTOPUS",
    "Oil & Gas Dev": "OGDC",
    "Oilboy Energy": "OBOY",
    "Olympia Mills": "OML",
    "Orient Rental": "ORM",
    "Otsuka Pak": "OTSU",
    "P.N.S.C": "PNSC",
    "P.S.O.": "PSO",
    "P.T.C.L.": "PTC",
  "PIA Holding Company": "PIAHCLA",  # Class "A" shares (Formerly PIAA)
    "PIA Holding CompanyB": "PIAHCLB" ,
 'PICIC Ins.Ltd.':'PICIC',
  "Pace (Pak) Ltd.": "PACE",
    "Packages Ltd.": "PKGS",
    "Pak Datacom": "PAKD",
    "Pak Elektron": "PAEL",
    "Pak Engineering": "PKEE",
    "Pak Gen.Ins.": "PGICL",
    "Pak Gulf Leasing": "PGLC",
    "Pak Int.Bulk": "PIBTL",
    "Pak Leather": "PLSM",
    "Pak Oilfields": "POL",
    "Pak Oxygen Ltd.": "PAKOXY",
    "Pak Paper Prod": "PPP",
    "Pak Petroleum": "PPL",
    "Pak Qatar Family": "PQFL",      # Pak-Qatar Family Takaful (verify listing status)
    "Pak Qatar General": "PQGICL",   # Pak-Qatar General Takaful
    "Pak Refinery": "PRL",
    "Pak Reinsurance": "PAKRI",
    "Pak Services": "PSEL",
    "Pak Stock Exchange": "PSX",
    "Pak Tobacco": "PAKT",
    "Pak.Int.Container": "PICT",
    "Pakgen Power": "PKGP",
    "Pakistan Alumin": "PABC",      # Pakistan Aluminium Beverages Cans
    "Pakistan Cables-": "PCAL",
    "Panther Tyres Ltd.": "PANTHER",
    "Paramount Mod": "PMOD",
    "Paramount Sp": "PSM",
    "Pervez Ahmed Co": "PACL",
    "Pioneer Cement": "PIOC",
    "Power Cem(Pref)": "PCLPS",     # Preference shares
    "Power Cement": "POWER",
    "Premier Ins.": "PINL",
    "Premium Tex.": "PREM",
    "Prosperity Weaving": "PRWM",
    "Punjab Mod": "FPM",           # First Punjab Modaraba
    "Punjab Oil": "POML",
    "Quantum Data": "QDL",         # Verify specific entity (formerly known under technology)
    "Quetta Textile": "QUET",
    "Quice Food": "QUICE",
    "Rafhan Maize": "RMPL",
    "Redco Textile": "REDCO",
    "Reliance Ins.": "RICL",
    "Reliance Weaving": "REWM",
    "Roshan Packages": "ROSH",
    "Ruby Textile": "RUBY",
    "S.G.Power": "SGPL",
    "S.S.Oil": "SSOM",
 'SPEL Limited':'SPEL',
"Safe Mix Con.Ltd": "SMCEL",
    "Saif Power Ltd": "SPWL",
    "Saif Textile": "SAIF",
    "Sakrand Sugar": "SKRS",
    "Sally Textile": "SALT",
    "Samba Bank": "SBL",
    "Sana Ind.": "SANA",
    "Sanghar Sugar": "SANSM",
    "Sapphire Fiber": "SFL",
    "Sapphire Tex.": "STML",
    "Sardar Chemical": "SARC",
    "Saritow Spinning": "SSML",
    "Sazgar Engineering": "SAZEW",
    "Sec. Inv. Bank": "SIBL",
    "Secure Logistics -Tr": "SLGL",
    "Security Paper": "SECP",
    "Service Global": "SGF",          # Service Global Footwear
    "Service Ind Tex": "SITM",
    "Service Ind.Ltd": "SRVI",
    "Shabbir Tiles": "STCL",
    "Shadab Textile": "SHDT",
    "Shadman Cotton": "SHACM",
    "Shaheen Ins.": "SILC",
    "Shahmurad Sugar": "SHSML",
    "Shahtaj Sugar": "SHJS",
    "Shahtaj Textile": "SHAT",
    "Shahzad Tex.": "SZTM",
    "Shakarganj Limited": "SML",
    "Shezan Inter.": "SHEZ",
    "Shield Corp.": "SHIELD",
    "Shifa Int.Hospital": "SHIFA",
    "Siddiqsons Tin": "STPL",
    "Siemens Pak.": "SIEM",
    "Signature Residency": "SRR",      # Signature Residency REIT
    "Sindh Abadgar": "SABS",
    "Sindh Modaraba": "SMOD",
    "Sitara Chemical": "SITC",
    "Sitara Energy": "SEL",
    "Sitara Peroxide": "SPL",
    "Soneri Bank Ltd": "SNBL",
    "St.Chart.Bank": "SCBPL",
    "Stylers Int.Ltd.": "SYLERS",      # Listed in late 2024
    "Sui North Gas": "SNGP",
    "Sui South Gas": "SSGC",
    "Sunrays Textile": "SUNT",
    "Supernet Technologie": "GEMSPNL", # Listed on GEM Board
    "Suraj Cotton Mills": "SURC",
    "Symmetry Group Ltd": "SYM",
    "Systems Limited": "SYS",
   "TPL Corp Ltd": "TPL",
    "TPL Insurance": "TPLI",
    "TPL Life Insurance": "TPLL",
    "TPL Properties": "TPLP",
    "TPL REIT Fund I": "TPLR1",
    "TPL Trakker Ltd": "TPLT",
 "Tandlianwala Sugar": "TSML",
    "Tariq Corp Ltd.": "TCORP",
    "Tariq Corp(Pref)": "TCORPCPS",
    "Tariq Glass Ind.": "TGL",
    "Tata Textile": "TATM",
    "Telecard Limited": "TELE",
    "Thal Ind.Corp.": "TICL",
    "Thal LimitedXD": "THALL",
    "Thatta Cement": "THCCL",
    "The Organic Meat": "TOMCL",
    "The Searle Company": "SEARL",
    "Towellers Limited": "TOWL",
    "Treet Battery Ltd.": "TBL",
    "Treet Corp": "TREET",
    "Tri-Pack Films": "TRIPF",
    "Tri-Star 1st Mod.": "FTSM",
    "Tri-Star Mutual": "TSMF",
    "Tri-Star Power": "TSPL",
    "Trust Brokerage": "TPL",
    "Trust Modaraba": "TRSTM",
    "Trust Sec. & Bro.(R)": "TSBLR1",
 "UBLPakistanETF": "UBLPGETF",
    "UDL Int.Ltd.": "UDL",  # Future Contract for Unity Foods
    "Unicap Modaraba": "UCAPM",
    "Unilever Foods": "UPFL",
    "United Bank": "UBL",
    "United Brands": "UBDL",
    "United Distributor": "UDPL",
    "United Insurance": "UICL",
    "Unity Foods Ltd": "UNITY",
    "Universal Network": "UNL",      # Future Contract for WorldCall
    'Wafi Energy Pak': 'WAFI',      # Wafi Energy Pakistan Limited
    'Wah-Noble': 'WAH',            # Wah-Noble Chemicals Limited
    'Wasl Mobility Mod': 'WASL',   # Wasl Mobility Modaraba
    'Waves Corp Ltd.': 'WAVES',
    'Waves Home App': 'WAVESAPP',
    'WorldCall Telecom': 'WTL',
    'Yousuf Weaving': 'YOUW',
    'ZIL Limited': 'ZIL',
    'ZahidJee Tex.': 'ZJTML',
    'Zarea Limited': 'ZAREA',
    'Zephyr Textile': 'ZEPHT',
    'Zuma Resources Ltd': 'ZRL'  }


shariah_data={
"ABOT": ["Abbott Lab (Pakistan) Ltd", "Compliant"],
"AGSML": ["Abdullah Shah Ghazi Sugar Mills Limited", "Non-Compliant"],
"ADAMS": ["Adam Sugar Mills Ltd", "Compliant"],
"AGHA": ["Agha Steel Ind Limited", "Non-Compliant"],
"AGP": ["AGP Limited", "Compliant"],
"AGIL": ["Agriauto Industries Ltd", "Compliant"],
"AGL": ["Agritech Limited", "Non-Compliant"],
"AIRLINK": ["Air Link Communication Limited", "Compliant"],
"ASL": ["Aisha Steel Ltd", "Compliant"],
"AKDHL": ["AKD Hospitality Limited (AKD Capital)", "Compliant"],
"AABS": ["Al-Abbas Sugar Mills Ltd", "Compliant"],
"AGTL": ["Al-Ghazi Tractors Ltd", "Compliant"],
"ALNRS": ["Al-Noor Sugar Mills Ltd", "Compliant"],
"ALTN": ["Altern Energy Ltd", "Non-Compliant"],
"ASTL": ["Amreli Steels Ltd", "Non-Compliant"],
"ARPL": ["Archroma Pakistan Ltd", "Compliant"],
"ARCTM": ["Arctic Textile Mills Limited", "Compliant"],
"AHCL": ["Arif Habib Corporation Ltd", "Non-Compliant"],
"ADMM": ["Artistic Denim Mills Ltd", "Non-Compliant"],
"ATBA": ["Atlas Battery Ltd", "Compliant"],
"ATLH": ["Atlas Honda Ltd", "Non-Compliant"],
"PREMA": ["At-Tahur Limited", "Compliant"],
"ACPL": ["Attock Cement Pakistan Ltd", "Compliant"],
"APL": ["Attock Petroleum Ltd", "Compliant"],
"ATRL": ["Attock Refinery Ltd", "Compliant"],
"AVN": ["Avanceon Limited", "Compliant"],
"ANL": ["Azgard Nine Ltd", "Compliant"],
"BRRG": ["B.R.R Guardian Limited", "Compliant"],
"BGL": ["Balochistan Glass Ltd", "Non-Compliant"],
"BWHL": ["Baluchistan Wheels Ltd", "Compliant"],
"BNWM": ["Bannu Woollen Mills Ltd", "Compliant"],
"BATA": ["Bata (Pakistan) Ltd", "Compliant"],
"BECO": ["Beco Steel Limited (Ravi Textile)", "Compliant"],
"BERG": ["Berger Paints Pakistan Ltd", "Compliant"],
"BWCL": ["Bestway Cement Ltd", "Non-Compliant"],
"BFBIO": ["BF Biosciences Limited", "Compliant"],
"BIFO": ["Biafo Industries Ltd", "Compliant"],
"BBFL": ["Big Bird Foods Limited", "Compliant"],
"BTL": ["Blessed Textiles Ltd", "Compliant"],
"BCL": ["Bolan Castings Ltd", "Compliant"],
"BNL": ["Bunnys Limited", "Compliant"],
"BPL": ["Burshane LPG (Pakistan) Ltd", "Compliant"],
"BUXL": ["Buxly Paints Ltd", "Compliant"],
"CASH": ["CALCORP Limited (Capital Assets Leasing Corporation)", "Non-Compliant"],
"CEPB": ["Century Paper & Board Mills", "Compliant"],
"CHAS": ["Chashma Sugar Mills Ltd", "Non-Compliant"],
"CHBL": ["Chenab Limited", "Non-Compliant"],
"CHCC": ["Cherat Cement Co. Ltd", "Compliant"],
"CPPL": ["Cherat Packaging Ltd", "Compliant"],
"CPHL": ["Citi Pharma Limited", "Compliant"],
"CLOV": ["Clover Pakistan Ltd", "Compliant"],
"CNERGY": ["Cnergyico PK Limited", "Compliant"],
"COLG": ["Colgate Palmolive (Pakistan)", "Non-Compliant"],
"CTM": ["Colony Textile Mills Ltd", "Non-Compliant"],
"CLVL": ["Cordoba Logistics", "Non-Compliant"],
"CSAP": ["Crescent Steel & Allied Products", "Compliant"],
"CRTM": ["Crescent Textile Mills Ltd", "Compliant"],
"CYAN": ["Cyan Limited", "Non-Compliant"],
"DGKC": ["D.G. Khan Cement Co. Ltd", "Compliant"],
"DADX": ["Dadex Eternit Limited", "Compliant"],
"DNCC": ["Dandot Cement Co. Ltd", "Compliant"],
"DAAG": ["Data Agro Limited", "Compliant"],
"DLL": ["Dawood Lawrencepur Limited", "Non-Compliant"],
"DOL": ["Descon Oxychem Ltd", "Compliant"],
"DCL": ["Dewan Cement Ltd", "Compliant"],
"DFSM": ["Dewan Farooq Spinning Mills Ltd", "Compliant"],
"DFML": ["Dewan Farooque Motors Ltd", "Non-Compliant"],
"DHPL": ["DH Partners Limited", "Non-Compliant"],
"DCR": ["Dolmen City REIT", "Compliant"],
"DSIL": ["DS Industries Ltd", "Non-Compliant"],
"DYNO": ["Dynea Pakistan Ltd", "Compliant"],
"ECOP": ["EcoPack Ltd", "Compliant"],
"EMCO": ["EMCO Industries Ltd", "Compliant"],
"EFERT": ["Engro Fertilizers Ltd", "Compliant"],
"ENGROH": ["Engro Holdings Limited (Dawood Hercules Corporation)", "Compliant"],
"EPCL": ["Engro Polymer & Chemicals", "Compliant"],
"EPQL": ["Engro Powergen Qadirpur Ltd", "Compliant"],
"EXIDE": ["Exide Pakistan Ltd", "Compliant"],
"FRSM": ["Faran Sugar Mills Ltd", "Compliant"],
"FCL": ["Fast Cables Limited", "Compliant"],
"FATIMA": ["Fatima Fertilizer Co. Ltd", "Compliant"],
"FCCL": ["Fauji Cement Co. Ltd", "Compliant"],
"FFC": ["Fauji Fertilizer Company Ltd", "Compliant"],
"FFL": ["Fauji Foods Ltd", "Compliant"],
"FZCM": ["Fazal Cloth Mills Ltd", "Compliant"],
"FECTC": ["Fecto Cement Ltd", "Compliant"],
"FML": ["Feroze1888 Mills Ltd", "Compliant"],
"FEROZ": ["Ferozsons Laboratories Ltd", "Compliant"],
"FDPL": ["First Dawood Properties Limited", "Non-Compliant"],
"FLYNG": ["FlyIng Cement Co. Ltd", "Compliant"],
"FCEPL": ["Frieslandcampins Engro Foods Limited", "Compliant"],
"FRCL": ["Frontier Ceramics Ltd", "Compliant"],
"GADT": ["Gadoon Textile Mills Ltd", "Non-Compliant"],
"GATI": ["Gatron (Industries) Ltd", "Compliant"],
"GALG": ["Ghandhara Automobiles Limited (Ghandhara Nissan Ltd)", "Compliant"],
"GHNI": ["Ghandhara Industries Ltd", "Compliant"],
"GTYR": ["Ghandhara Tyre & Rubber Co.", "Compliant"],
"GCIL": ["Ghani Chemical Industries Ltd", "Compliant"],
"GHGL": ["Ghani Glass Ltd", "Compliant"],
"GGGL": ["Ghani Global Glass Ltd", "Compliant"],
"GGL": ["Ghani Global Holdings Limited", "Compliant"],
"GVGL": ["Ghani Value Glass Ltd", "Compliant"],
"GWLC": ["Gharibwal Cement Ltd", "Compliant"],
"GFIL": ["Ghazi Fabrics International Ltd", "Compliant"],
"GLPL": ["Gillette Pakistan Ltd", "Compliant"],
"GLAXO": ["GlaxoSmithKline Pakistan", "Compliant"],
"GOC": ["GOC (Pakistan) Limited", "Compliant"],
"GATM": ["Gul Ahmed Textile Mills Ltd", "Compliant"],
"HRPL": ["Habib Rice Products Ltd", "Compliant"],
"HABSM": ["Habib Sugar Mills Ltd", "Compliant"],
"HAEL": ["Hala Enterprises Ltd", "Compliant"],
"HALEON": ["Haleon Pakistan Limited (Glaxo SmithKline Consumer Healthcare)", "Compliant"],
"HINOON": ["Highnoon Laboratories Ltd", "Compliant"],
"HINO": ["Hinopak Motors Ltd", "Compliant"],
"HTL": ["Hi-Tech Lubricants Ltd", "Compliant"],
"HPL": ["Hoechst Pakistan Limited (Sanofi Aventis)", "Compliant"],
"HCAR": ["Honda Atlas Cars (Pakistan) Ltd", "Compliant"],
"HUBC": ["Hub Power Company Ltd", "Compliant"],
"IBLHL": ["IBL HealthCare Ltd", "Compliant"],
"IBFL": ["Ibrahim Fibres Ltd", "Compliant"],
"ICCI": ["ICC Industries Limited", "Compliant"],
"IDRT": ["Idrees Textile Mills Ltd", "Compliant"],
"IMAGE": ["Image Pakistan Limited", "Compliant"],
"IDYM": ["Indus Dyeing & Mfg Co. Ltd", "Non-Compliant"],
"INDU": ["Indus Motor Company Ltd", "Non-Compliant"],
"ILP": ["Interloop Limited", "Compliant"],
"INIL": ["International Industries Ltd", "Compliant"],
"INKL": ["International Knitwear Ltd", "Non-Compliant"],
"IPAK": ["International Packaging Films Limited", "Compliant"],
"ISL": ["International Steels Ltd", "Compliant"],
"ISIL": ["Ismail Industries Ltd", "Compliant"],
"ITTEFAQ": ["Ittefaq Iron Industries", "Compliant"],
"ICL": ["Ittehad Chemicals Ltd", "Compliant"],
"JDMT": ["Janana De Malucho Textile", "Compliant"],
"JSML": ["Jauharabad Sugar Mills Ltd", "Compliant"],
"JVDC": ["Javedan Corporation Ltd", "Compliant"],
"JDWS": ["JDW Sugar Mills Ltd", "Compliant"],
"KSBP": ["K.S.B.Pumps Company Ltd", "Compliant"],
"KEL": ["K-Electric Ltd", "Compliant"],
"KPUS": ["Khairpur Sugar Mills Ltd", "Compliant"],
"KOHC": ["Kohat Cement Co. Ltd", "Compliant"],
"KOHTM": ["Kohat Textile Mills Limited", "Compliant"],
"KOHE": ["Kohinoor Energy Ltd", "Compliant"],
"KOIL": ["Kohinoor Industries Ltd", "Non-Compliant"],
"KML": ["Kohinoor Mills Ltd", "Compliant"],
"KOHP": ["Kohinoor Power Company", "Non-Compliant"],
"KOSM": ["Kohinoor Spinning Mills Ltd", "Non-Compliant"],
"KTML": ["Kohinoor Textile Mills Ltd", "Compliant"],
"KAPCO": ["Kot Addu Power Company", "Non-Compliant"],
"LPL": ["Lalpir Power Ltd", "Non-Compliant"],
"LEUL": ["Leather-Up Limited", "Compliant"],
"LPGL": ["Leiner Pak Gelatine Ltd", "Compliant"],
"LIVEN": ["Liven Pharma Limited", "Compliant"],
"LOADS": ["Loads Limited", "Compliant"],
"LOTCHEM": ["Lotte Chemical Pakistan Ltd", "Compliant"],
"LSECL": ["LSE Capital Limited", "Non-Compliant"],
"LUCK": ["Lucky Cement Ltd", "Compliant"],
"LCI": ["Lucky Core Industries Limited (ICI Pakistan)", "Compliant"],
"MACFL": ["MACPAC Films Ltd", "Compliant"],
"MACTER": ["Macter International Ltd", "Compliant"],
"MWMP": ["Mandviwala Mauser Plastic Industries", "Compliant"],
"MLCF": ["Maple Leaf Cement Factory", "Compliant"],
"MARI": ["Mari Energies Ltd", "Compliant"],
"MSOT": ["Masood Textile Mills", "Non-Compliant"],
"MFL": ["Matco Foods Ltd", "Compliant"],
"MEHT": ["Mehmood Textile Mills Ltd", "Compliant"],
"MRNS": ["Mehran Sugar Mills Ltd", "Non-Compliant"],
"MERIT": ["Merit Packaging Ltd", "Compliant"],
"MSCL": ["Metropolitan Steel Corporation", "Compliant"],
"MTL": ["Millat Tractors Ltd", "Compliant"],
"MIRKS": ["Mirpurkhas Sugar Mills Ltd", "Non-Compliant"],
"MFFL": ["Mitchell's Fruit Farms Ltd", "Compliant"],
"MUGHAL": ["Mughal Iron & Steel Industries", "Compliant"],
"NATF": ["National Foods Ltd", "Compliant"],
"NRL": ["National Refinery Ltd", "Compliant"],
"NESTLE": ["Nestle Pakistan Ltd", "Compliant"],
"NETSOL": ["Netsol Technologies Ltd", "Compliant"],
"NICL": ["Nimir Industrial Chemicals Ltd", "Non-Compliant"],
"NRSL": ["Nimir Resins Ltd", "Compliant"],
"NCL": ["Nishat (Chunian) Ltd", "Non-Compliant"],
"NCPL": ["Nishat Chunian Power Ltd", "Non-Compliant"],
"NML": ["Nishat Mills Ltd", "Compliant"],
"NPL": ["Nishat Power Limited", "Non-Compliant"],
"NONS": ["Noon Sugar Mills Ltd", "Non-Compliant"],
"OCTOPUS": ["Octopus Digital Limited", "Compliant"],
"OGDC": ["Oil & Gas Development Co. Ltd", "Compliant"],
"OBOY": ["Oilboy Energy Limited (Drekkar Kingsway Ltd)", "Compliant"],
"OML": ["Olympia Mills Ltd", "Compliant"],
"OTSU": ["Otsuka Pakistan Ltd", "Non-Compliant"],
"PACE": ["Pace (Pakistan) Ltd", "Non-Compliant"],
"PKGS": ["Packages Limited", "Compliant"],
"PAKD": ["Pak DataCom Ltd", "Compliant"],
"PAEL": ["Pak Elektron Ltd", "Compliant"],
"PKGP": ["Pakgen Power Ltd", "Non-Compliant"],
"PABC": ["Pakistan Aluminium Beverages", "Non-Compliant"],
"PCAL": ["Pakistan Cables Ltd", "Non-Compliant"],
"PIBTL": ["Pakistan International Bulk Terminal Ltd", "Compliant"],
"PICT": ["Pakistan International Container Terminal", "Non-Compliant"],
"PNSC": ["Pakistan National Shipping Corporation", "Non-Compliant"],
"POL": ["Pakistan Oilfields Ltd", "Non-Compliant"],
"PAKOXY": ["Pakistan Oxygen Limited", "Compliant"],
"PPP": ["Pakistan Paper Products Ltd", "Compliant"],
"PPL": ["Pakistan Petroleum Limited", "Compliant"],
"PRL": ["Pakistan Refinery Ltd", "Compliant"],
"PSEL": ["Pakistan Services Ltd", "Compliant"],
"PSO": ["Pakistan State Oil Co. Ltd", "Compliant"],
"PSX": ["Pakistan Stock Exchange Ltd", "Non-Compliant"],
"PSYL": ["Pakistan Synthetics Ltd", "Compliant"],
"PTC": ["Pakistan Telecommunication (PTCL)", "Non-Compliant"],
"PTL": ["Panthar Tyres Limited", "Compliant"],
"PIOC": ["Pioneer Cement Ltd", "Compliant"],
"POWER": ["Power Cement Ltd", "Compliant"],
"PRET": ["Premium Textile Mills Ltd", "Non-Compliant"],
"PRWM": ["Prosperity Weaving Mills Ltd", "Non-Compliant"],
"POML": ["Punjab Oil Mills Ltd", "Compliant"],
"QUICE": ["Quice Food Industries Ltd", "Compliant"],
"RMPL": ["Rafhan Maize Products", "Compliant"],
"REDCO": ["Redco Textiles Ltd", "Compliant"],
"RCML": ["Reliance Cotton Spinning", "Compliant"],
"RPL": ["Roshan Packages Ltd", "Compliant"],
"RUPL": ["Rupali Polyester Ltd", "Compliant"],
"SSOM": ["S.S. Oil Mills Ltd", "Compliant"],
"SMCPL": ["Safe Mix Concrete Ltd", "Compliant"],
"SPWL": ["Saif Power Ltd", "Compliant"],
"SAIF": ["Saif Textile Mills Ltd", "Compliant"],
"SNAI": ["Sana Industries Ltd", "Compliant"],
"SANSM": ["Sanghar Sugar Mills Ltd", "Compliant"],
"SFL": ["Sapphire Fibres Ltd", "Non-Compliant"],
"SAPT": ["Sapphire Textile Mills", "Compliant"],
"SARC": ["Sardar Chemical Industries", "Compliant"],
"SAZEW": ["Sazgar Engineering Works", "Compliant"],
"SEARL": ["Searle Company Ltd", "Compliant"],
"SLGL": ["Secure Logistics Group Limited", "Compliant"],
"SEPL": ["Security Papers Ltd", "Non-Compliant"],
"SGF": ["Service Global Footwear Limited", "Compliant"],
"SRVI": ["Service Industries Ltd", "Non-Compliant"],
"SERT": ["Service Industries Textiles Limited", "Compliant"],
"SGPL": ["SG Power Ltd", "Compliant"],
"STCL": ["Shabbir Tiles & Ceramics Ltd", "Compliant"],
"SHDT": ["Shadab Textile Mills Ltd", "Compliant"],
"SHSML": ["Shahmurad Sugar Mills Ltd", "Compliant"],
"SHJS": ["Shahtaj Sugar Mills Ltd", "Non-Compliant"],
"SHEZ": ["Shezan International Ltd", "Compliant"],
"SCL": ["Shield Corporation Ltd", "Compliant"],
"SHFA": ["Shifa International Hospitals", "Compliant"],
"SIEM": ["Siemens (Pakistan) Engineering Co Limited", "Compliant"],
"SASML": ["Sindh Abadgar's Sugar Mills Ltd", "Non-Compliant"],
"SITC": ["Sitara Chemical Industries Ltd", "Compliant"],
"STYLERS": ["Stylers International Limited (AEL Textile Limited)", "Compliant"],
"SNGP": ["Sui Northern Gas Pipelines Ltd", "Compliant"],
"SSGC": ["Sui Southern Gas Co. Ltd", "Compliant"],
"SUTM": ["Sunrays Textile Mills Ltd", "Non-Compliant"],
"STL": ["Supernet Technologies Limited", "Compliant"],
"SYM": ["Symmetry Group Limited", "Compliant"],
"SPEL": ["Synthetic Products Ltd", "Compliant"],
"SYS": ["Systems Limited", "Compliant"],
"TCORP": ["Tariq Corporation Ltd", "Compliant"],
"TGL": ["Tariq Glass Industries Ltd", "Compliant"],
"TATM": ["TATA Textile Mills Ltd", "Compliant"],
"TELE": ["Telecard Limited", "Compliant"],
"THALL": ["Thal Limited", "Non-Compliant"],
"THCCL": ["Thatta Cement Company", "Non-Compliant"],
"TOMCL": ["The Organic Meat Company", "Compliant"],
"TOWL": ["Towellers Limited", "Compliant"],
"TPL": ["TPL Corporation", "Non-Compliant"],
"TPLP": ["TPL Properties Ltd", "Compliant"],
"TPLRF1": ["TPL REIT Fund 1", "Compliant"],
"TPLT": ["TPL Trakker Ltd", "Compliant"],
"TBL": ["Treet Battery Limited", "Compliant"],
"TREET": ["Treet Corporation Ltd", "Compliant"],
"TRG": ["TRG Pakistan Ltd", "Non-Compliant"],
"TRIPF": ["Tri-Pack Films Ltd", "Non-Compliant"],
"TSPL": ["Tri-Star Power Ltd", "Non-Compliant"],
"UDLI": ["UDL International Limited", "Compliant"],
"UBDL": ["United Brands Limited", "Compliant"],
"UDPL": ["United Distributors (Pakistan) Ltd", "Compliant"],
"UNITY": ["Unity Foods Ltd", "Non-Compliant"],
"WAFI": ["Wafi Energy Pakistan Limited (Shell Pakistan Limited)", "Compliant"],
"WAHN": ["Wah-Noble Chemicals Ltd", "Compliant"],
"WAVES": ["Waves Corporation Limited", "Compliant"],
"WAVESAPP": ["Waves Home Appliances Limited", "Non-Compliant"],
"WTL": ["WorldCall Telecom Ltd", "Non-Compliant"],
"YOUW": ["Yousaf Weaving Mills Ltd", "Compliant"],
"ZIL": ["ZIL Limited", "Compliant"],
"BFMOD": ["B.F. Modaraba", "Compliant"],
"BIPL": ["BankIslami Pakistan Ltd", "Compliant"],
"FABL": ["Faysal Bank Ltd", "Compliant"],
"FECM": ["First Elite Capital Modaraba", "Compliant"],
"FEM": ["First Equity Modaraba", "Compliant"],
"FFLM": ["First Fidelity Leasing Modaraba", "Compliant"],
"FHAM": ["First Habib Modaraba", "Compliant"],
"FPRM": ["First Paramount Modaraba", "Compliant"],
"FPJM": ["First Punjab Modaraba", "Compliant"],
"FTMM": ["First Treet Manufacturing Modaraba", "Compliant"],
"FTSM": ["First Tri-Star Modaraba", "Compliant"],
"MEBL": ["Meezan Bank Ltd", "Compliant"],
"OLPM": ["OLP Modaraba (Orix Modaraba)", "Compliant"],
"ORM": ["Orient Rental Modaraba", "Compliant"],
"PIM": ["Popular Islamic Modaraba", "Compliant"],
"SINDM": ["Sindh Modaraba", "Compliant"],
"TRSM": ["Trust Modaraba", "Compliant"],
"UCAPM": ["Unicap Modaraba", "Compliant"],
"WASL": ["Wasl Mobility Modaraba (First Prudential Modaraba)", "Compliant"]
}

stock_data={'AGTL': 0.65,
 'ATLH': 0.67,
 'DFML': 1.19,
 'GAL': 1.38,
 'GHNI': 1.31,
 'HINO': 0.85,
 'HCAR': 1.07,
 'INDU': 0.42,
 'MTL': 0.61,
 'SAZEW': 1.11,
 'AIGL': 0.87,
 'ATBA': 0.83,
 'BELA': 2.63,
 'DWAE': 0.85,
 'EXIDE': 0.84,
 'GTYR': 1.19,
 'LOADS': 1.23,
 'PANTHER': 1.08,
 'TBL': 0.84,
 'EMCO': 0.68,
 'FCL': 0.77,
 'PAEL': 1.42,
 'PCAL': 0.74,
 'SIEM': 0.22,
 'WAVES': 1.15,
 'WAVESAPP': 1.11,
 'ACPL': 0.86,
 'BWCL': 0.74,
 'CHCC': 1.16,
 'DGKC': 1.37,
 'DBCI': 1.19,
 'DNCC': 0.88,
 'DCL': 1.37,
 'FCCL': 1.33,
 'FECTC': 1.17,
 'FLYNG': 1.08,
 'GWLC': 1.21,
 'KOHC': 1.21,
 'LUCK': 1.28,
 'MLCF': 1.33,
 'PIOC': 1.21,
 'PCLPS': 1.11,
 'POWER': 1.1,
 'SMCEL': 0.76,
 'THCCL': 0.95,
 'ARPL': 0.63,
 'BAPL': 0.54,
 'BERL': 1.01,
 'BIFO': 0.83,
 'BUXL': 0.58,
 'DAAG': 0.61,
 'DOL': 0.74,
 'DYNO': 0.86,
 'EPCLP': 0.83,
 'EPCL': 0.84,
 'GCIL': 1.12,
 'GCWL': 1.29,
 'GGL': 1.28,
 'ICL': 0.72,
 'LPGL': 0.81,
 'LOTCHEM': 0.89,
 'LCI': 0.64,
 'NICL': 0.69,
 'NRSL': 0.86,
 'PAKOXY': 0.78,
 'SARC': 0.38,
 'SITC': 0.56,
 'SPL': 0.65,
 'WAH': 0.61,
 'HGFA': 0.91,
 'HIFA': 1.47,
 'TSMF': 0.44,
 'ABL': 0.62,
 'AKBL': 1.1,
 'BAFL': 1.03,
 'BAHL': 0.93,
 'BML': 1.35,
 'FABL': 1.1,
 'HBL': 1.1,
 'HMB': 0.77,
 'JSBL': 0.83,
 'MCB': 0.88,
 'MEBL': 0.96,
 'NBP': 1.18,
 'SBL': 0.54,
 'SNBL': 0.76,
 'UBL': 1.11,
 'AGHA': 1.15,
 'ASL': 1.17,
 'ASLCPS': -0.42,
 'ASTL': 1.01,
 'BECO': 1.12,
 'BCL': 0.85,
 'DADX': 0.37,
 'DSL': 0.81,
 'ITTEFAQ': 1.2,
 'KSBP': 0.81,
 'MSCL': 0.51,
 'MUGH': 1.30,
 'MUGHALC': 0.41,
 'PKEE': 0.56,
 'ACIETF': None,
 'HBLTETF': None,
 'JSMFETF': None,
 'MIIETF': None,
 'MZNPAK': None,
 'NBPGETF': None,
 'NITGETF': None,
 'UBLPGETF': None,
 'AGL': 1.05,
 'AHCL': 0.92,
 'EFERT': 0.88,
 'FFC': 0.91,
 'ASC': 1.08,
 'PREMA': 1.07,
 'BFAL': 1.06,
 'BBFL': 0.91,
 'BNL': 0.9,
 'CLOV': 0.95,
 'COLG': 0.44,
 'FFL': 1.22,
 'FCEPL': 1.07,
 'GDL': 0.45,
 'GILL': 0.25,
 'ISIL': 0.3,
 'MATCO': 0.90,
 'MFFL': 0.95,
 'MUREB': 0.52,
 'NATF': 0.83,
 'NESTLE': 0.26,
 'QUICE': 1.15,
 'RMPL': 0.25,
 'SHEZ': 0.88,
 'SHIELD': 0.22,
 'TOMCL': 1.12,
 'TREET': 1.27,
 'UPFL': 0.27,
 'UNITY': 0.86,
 'ZIL': 0.29,
 '': None,
 'BGL': 1.03,
 'GHGL': 1.03,
 'GVGL': 0.56,
 'GGGL': 1.15,
 'STCL': 0.93,
 'AICL': 0.97,
 'ALIFE': 0.61,
 'ASIC': 0.05,
 'AGIC': 0.53,
 'ALAC': 0.69,
 'CENI': 0.39,
 'CSIL': 1.21,
 'EFUG': 0.33,
 'EFUL': 0.28,
 'HICL': 0.56,
 'IGIHL': 0.85,
 'JLIU': 0.5,
 'PGICL': 0.37,
 'PQFL': 0.78,
 'PQGICL': 0.78,
 'PAKRI': 0.88,
 'PICIC': 1.19,
 'PINL': 0.63,
 'TPLI': 0.41,
 'TPLL': -0.26,
 'UICL': 0.22,
 '786': 0.14,
 'AKD': 0.43,
 'AMBL': 0.09,
 'AHL': 0.97,
 'DEL': 0.66,
 'DLL': 0.42,
 'ENGRO': 0.87,
 'ESBL': 0.77,
 'FNEL': 1.37,
 'FCIBL': 0.31,
 'FCE': 0.67,
 'FDPL': 1.35,
 'IML': 0.44,
 'IMS': 0.85,
 'ICIBL': 1.1,
 'FCSC': 1.31,
 'JSCL': 1.12,
 'JSGCL': 0.28,
 'JSIL': 0.66,
 'LSECAP': 1.04,
 'LSEFSL': 0.52,
 'LSEV': 0.57,
 'NEXT': 0.41,
 'OLPL': 0.47,
 'PSX': 1.29,
 'PACL': 1.22,
 'PIAHCLA': 1.05,
 'PIAHCLB': 10.45,
 'SIBL': 0.47,
 'TPL': 1.29,
 'CJUM': 0.74,
 'GRYL': 0.31,
 'PGLC': 0.38,
 'BATA': 0.33,
 'FIL': 0.03,
 'LEUL': 0.43,
 'PLSM': 0.07,
 'SGF': 0.93,
 'SRVI': 0.9,
 'AKGL': 0.05,
 'ARPAK': -0.21,
 'ECOP': 0.83,
 'GAMON': 0.68,
 'GOC': 0.25,
 'MWMT': 0.45,
 'OML': 0.1,
 'PSEL': 0.42,
 'PABC': 0.89,
 'SHIFA': 0.83,
 'STPL': 1.0,
 'TRIPF': 0.6,
 'UDL': 0.63,
 'UBDL': 0.76,
 'UDPL': 0.54,
 'fid': 0.44,
 'FANM': 0.83,
 'BFMOD': 0.65,
 'ECAM': 0.45,
 'EQMOD': 0.65,
 'FTMM': 0.6,
 'FHAM': 0.32,
 'IBLMC': 0.67,
 'FIMM': 0.15,
 'OLPM': 0.24,
 'ORM': 0.52,
 'PMOD': None,
 'FPM': 0.26,
 'SMOD': 0.39,
 'FTSM': 0.35,
 'TRSTM': 0.82,
 'UCAPM': 1.1,
 'WASL': 0.89,
 'MARI': 1.05,
 'OGDC': 1.24,
 'POL': 0.61,
 'PPL': 1.36,
 'APL': 0.92,
 'BPL': 0.57,
 'HASCOL': 1.22,
 'HTL': 1.27,
 'OBOY': 0.92,
 'PSO': 1.34,
 'SNGP': 1.23,
 'SSGC': 1.32,
 'WAFI': 0.97,
 'CEPB': 1.18,
 'CPPL': 0.96,
 'IPAK': 0.6,
 'MACFL': 0.83,
 'MERIT': 0.64,
 'PKGS': 0.81,
 'PPP': 0.67,
 'ROSH': 1.07,
 'SECP': 0.74,
 'SPEL': 1.07,
 'ABBT': 0.88,
 'AGP': 0.97,
 'BFBIO': 1.21,
 'CPHL': 1.15,
 'FEROZ': 1.14,
 'GLAXO': 1.07,
 'HALEON': 0.89,
 'HINOON': 0.71,
 'IBLHL': 0.95,
 'LPL': 0.85,
 'MACTER': 0.44,
 'OTSU': 0.77,
 'SEARL': 1.37,
 'ALTN': 0.59,
 'EPQL': 0.39,
 'HUBC': 1.12,
 'KEL': 1.39,
 'KOHE': 0.5,
 'KOHP': 1.13,
 'KAPCO': 0.69,
 'NCPL': 1.03,
 'NPL': 0.97,
 'PKGP': 0.49,
 'SGPL': 0.87,
 'SPWL': 0.64,
 'SEL': 0.36,
 'TSPL': 0.85,
 'BRRG': 0.16,
 'HUSI': 0.42,
 'JVDCPS': 0.18,
 'JVDC': 0.71,
 'PACE': 1.38,
 'TPLP': 1.23,
 'DCR': 0.35,
 'GRR': 0.34,
 'IMREIT': 0.62,
 'SRR': 0.15,
 'TPLR1': 0.37,
 'ATRL': 1.11,
 'CNERGY': 1.45,
 'NRL': 1.33,
 'PRL': 1.35,
 'AGSML': 0.88,
 'ADAMS': 0.23,
 'AABS': 0.36,
 'ALNRS': 0.3,
 'ANSM': 0.43,
 'BAFS': 0.16,
 'CHAS': 0.55,
 'DWSM': 1.11,
 'FRSM': 0.34,
 'HRPL': 0.39,
 'HABSM': 0.42,
 'JDWS': 0.24,
 'JAUHS': 0.80,
 'KPUS': -0.05,
 'MRNS': 0.61,
 'MIRKS': 0.71,
 'NOON': 0.33,
 'SKRS': 0.36,
 'SANSM': 0.26,
 'SHSML': 0.35,
 'SHJS': 0.13,
 'SML': 0.22,
 'SABS': 0.37,
 'TSML': -0.19,
 'TCORP': 0.36,
 'TCORPCPS': 0.36,
 'TICL': 0.19,
 'GATI': 0.63,
 'IBFL': 0.23,
 'IMAGE': 1.15,
 'NSIL': 1.19,
 'AIRLINK': 1.34,
 'AVN': 1.08,
 'HUMNL': 1.0,
 'ITANZ': -1.11,
 'WTL': 1.35,
 'NETSOL': 1.16,
 'OCTOPUS': 1.1,
 'PTC': 1.37,
 'PAKD': 0.71,
 'QDL': 0.95,
 'GEMSPNL': 0.43,
 'SYM': 1.03,
 'SYS': 1.01,
 'TELE': 1.48,
 'TPLT': 0.86,
 'ZAREA': 0.95,
 'AHTM': 0.13,
 'ADMM': 0.49,
 'ARUJ': 0.54,
 'ANL': 1.07,
 'BHAT': 0.21,
 'CHBL': 1.03,
 'CHBLP': 1.05,
 'CRTM': 0.61,
 'FASM': 0.18,
 'FSWL': 0.04,
 'FZCM': 0.44,
 'FML': 0.47,
 'GFIL': 0.56,
 'GATM': 1.09,
 'HAEL': 0.94,
 'HALA': 0.93,
 'INKL': 0.06,
 'JUSM': 0.17,
 'KHYT': -0.15,
 'KOIL': 0.77,
 'KML': 0.5,
 'KTML': 1.18,
 'MSOT': 0.56,
 'MEHT': 0.41,
 'NCL': 1.04,
 'NML': 1.24,
 'PSM': 0.26,
 'QUET': 0.39,
 'REDCO': 0.36,
 'SFL': 0.23,
 'STML': 0.0,
 'SYLERS': 0.38,
 'SURC': 0.12,
 'TOWL': 0.69,
 'ZJTML': 0.37,
 'AATM': 0.1,
 'AMTEX': 1.07,
 'ARCTM': 0.35,
 'ASTM': 0.54,
 'CTM': 1.12,
 'CRFG': 0.12,
 'DMCO': 0.09,
 'DSIL': 1.23,
 'DFSM': 1.34,
 'DWTM': 0.34,
 'DINT': -0.08,
 'ELCM': -0.04,
 'ELLCOT': 0.39,
 'GADT': 0.68,
 'GSPM': 0.71,
 'HIRAT': 1.68,
 'IDSM': 0.3,
 'IDRT': 0.06,
 'IDYM': 0.66,
 'JATM': 0.33,
 'JDMT': 0.48,
 'KSTM': 0.58,
 'KOTM': 0.50,
 'KOSM': 1.69,
 'MQTM': -0.23,
 'NAGC': 0.22,
 'NZCM': 0.54,
 'PREM': 1.11,
 'RUBY': 0.68,
 'SAIF': 0.83,
 'SALT': 0.63,
 'SANA': 0.38,
 'SSML': 0.66,
 'SITM': 0.90,
 'SHDT': 0.47,
 'SHACM': 0.32,
 'SZTM': -0.24,
 'SUNT': 0.33,
 'TATM': 0.74,
 'ASHT': -0.11,
 'ICCI': 0.46,
 'PRWM': 0.26,
 'SHAT': 0.14,
 'YOUW': 1.31,
 'ZEPHT': 0.83,
 'KHTC': 0.56,
 'BLUEX': 0.09,
 'CLVL': 0.55,
 'PNSC': 0.9,
 'PIBTL': 1.31,
 'PICT': 0.7,
 'SLGL': 1.05,
 'POML': 0.63,
 'SSOM': 0.73,
 'BNWM': 0.65,
 'NETS': 0.21}

@app.route('/scrape_and_insert', methods=['GET'])
def scrape_and_insert():
    print("⏳ Scraping started from Flask endpoint...", datetime.now())

    url = "https://www.psx.com.pk/market-summary/"
    try:
        webpage = requests.get(url).text
        soup = BeautifulSoup(webpage, 'lxml')
    except requests.exceptions.RequestException as e:
        return jsonify({"status": "error", "message": f"Failed to fetch webpage: {e}"}), 500

    tables = soup.find_all('div', class_="table-responsive")
    all_sector_data = []

    for i in range(2, len(tables)): # Start from index 2 to skip first two tables (header/summary)
        table = tables[i]
        sector_name_tag = table.find('h4')
        sector_name = sector_name_tag.get_text(strip=True) if sector_name_tag else "Unknown Sector"

        tbody = table.find('tbody')
        if tbody:
            rows = tbody.find_all('tr')
        else:
            rows = table.find_all('tr')[1:] # Assuming first row might be header if no tbody

        sector_rows = []
        for row in rows:
            cols = row.find_all('td')
            if len(cols) >= 8: # Ensure enough columns are present
                scrip = cols[0].get_text(strip=True)
                symbol = company_symbol_dict.get(scrip, '')

                if not symbol: # Skip if symbol not found in our dict
                    continue
                
                # Clean and convert numeric fields
                try:
                    ldcp = float(cols[1].get_text(strip=True).replace(',', ''))
                    open_price = float(cols[2].get_text(strip=True).replace(',', ''))
                    high = float(cols[3].get_text(strip=True).replace(',', ''))
                    low = float(cols[4].get_text(strip=True).replace(',', ''))
                    current = float(cols[5].get_text(strip=True).replace(',', ''))
                    
                    change_text = cols[6].get_text(separator=' ', strip=True)
                    # Use regex to find numeric part of change
                    change_match = re.search(r'[-+]?\d*\.?\d+', change_text)
                    change = float(change_match.group(0)) if change_match else 0.0

                    volume = int(cols[7].get_text(strip=True).replace(',', ''))
                except ValueError as e:
                    print(f"Warning: Could not convert numeric data for {scrip} ({symbol}): {e}. Skipping.")
                    continue # Skip this row if numeric conversion fails

                shariah_status = shariah_data.get(symbol, [None, 'Non-Compliant'])[1] # Default to Non-Compliant
                beta = stock_data.get(symbol, 1.0) # Default BETA to 1.0 if not found

                # Determine RiskLevel
                if beta < 1:
                    risk_level = 'Low Risk'
                elif beta > 1:
                    risk_level = 'High Risk'
                else:
                    risk_level = 'Moderate Risk'
                
                sector_rows.append({
                    'scrip': scrip,
                    'symbol': symbol,
                    'ldcp': ldcp,
                    'open': open_price,
                    'high': high,
                    'low': low,
                    'current': current,
                    'change': change,
                    'volume': volume,
                    'shariah_status': shariah_status,
                    'beta': beta,
                    'risk_level': risk_level,
                    'sector': sector_name # Add sector here
                })
        if sector_rows:
            all_sector_data.extend(sector_rows)




            