"""alter int to float in  stock table

Revision ID: 03c7730fd697
Revises: f86e2c6af1f7
Create Date: 2026-04-28 11:54:25.893128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03c7730fd697'
down_revision: Union[str, Sequence[str], None] = 'f86e2c6af1f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        ALTER TABLE stocks 
        ALTER COLUMN open TYPE DOUBLE PRECISION USING open::double precision,
        ALTER COLUMN high TYPE DOUBLE PRECISION USING high::double precision,
        ALTER COLUMN low TYPE DOUBLE PRECISION USING low::double precision,
        ALTER COLUMN current_price TYPE DOUBLE PRECISION USING current_price::double precision,
        ALTER COLUMN change TYPE DOUBLE PRECISION USING change::double precision,
        ALTER COLUMN beta TYPE DOUBLE PRECISION USING beta::double precision;
    """)
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
