"""create stock table

Revision ID: 91af7c09ae87
Revises: 
Create Date: 2026-04-27 12:39:17.437576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91af7c09ae87'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migrations')
    op.drop_table('prediction_history')
    op.drop_table('stock')
    op.drop_index(op.f('IDX_c09950e1821cd0f8d0a9633367'), table_name='risk_answers')
    op.drop_index(op.f('IDX_fcebac831763703a306ef754f7'), table_name='risk_answers')
    op.drop_table('risk_answers')
    op.drop_index(op.f('IDX_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), server_default=sa.text("'user'::character varying"), autoincrement=False, nullable=False),
    sa.Column('riskCategory', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_cace4a159ff9f2512dd42373760'))
    )
    op.create_index(op.f('IDX_user_email'), 'user', ['email'], unique=False)
    op.create_table('risk_answers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('questionId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('questionText', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quizAnswer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name=op.f('FK_f357ba9a74c1143e85a3ca6bea2')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_aae9faa57a4133cd358b2d57484'))
    )
    op.create_index(op.f('IDX_fcebac831763703a306ef754f7'), 'risk_answers', ['userId', 'questionId'], unique=False)
    op.create_index(op.f('IDX_c09950e1821cd0f8d0a9633367'), 'risk_answers', ['createdAt'], unique=False)
    op.create_table('stock',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Ticker', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('CompanyName', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('OpenPrice', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ClosePrice', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('DailyReturn', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('CAGR', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Volatility', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('RiskScore', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('RiskLevel', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Sector', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('SharesOutstanding', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('MarketCap', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_092bc1fc7d860426a1dec5aa8e9'))
    )
    op.create_table('prediction_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('prediction', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('recommendation', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('reasoning', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('risks', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_97cc0a8087892d52d7691bddfa6'))
    )
    op.create_table('migrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_8c82d7f526340ab734260ea46be'))
    )
    # ### end Alembic commands ###
