"""add some columns in  stock table

Revision ID: f86e2c6af1f7
Revises: 91af7c09ae87
Create Date: 2026-04-27 12:50:54.747818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f86e2c6af1f7'
down_revision: Union[str, Sequence[str], None] = '91af7c09ae87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('open', sa.Integer(), nullable=True))
    op.add_column('stocks', sa.Column('high', sa.Integer(), nullable=True))
    op.add_column('stocks', sa.Column('low', sa.Integer(), nullable=True))
    op.add_column('stocks', sa.Column('current_price', sa.Integer(), nullable=True))
    op.add_column('stocks', sa.Column('risk_level', sa.String(), nullable=True))
    op.create_index(op.f('ix_stocks_risk_level'), 'stocks', ['risk_level'], unique=False)
    op.create_index(op.f('ix_stocks_sector'), 'stocks', ['sector'], unique=False)
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=False)
    op.drop_column('stocks', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_sector'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_risk_level'), table_name='stocks')
    op.drop_column('stocks', 'risk_level')
    op.drop_column('stocks', 'current_price')
    op.drop_column('stocks', 'low')
    op.drop_column('stocks', 'high')
    op.drop_column('stocks', 'open')
    # ### end Alembic commands ###
